source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QDStepsController_Example', :exclusive => true do
  pod 'QDStepsController', :path => '../'
end

target 'QDStepsController_Tests', :exclusive => true do
  pod 'QDStepsController', :path => '../'

  
end
